version: 1.0.{build}
os: WMF 5
skip_commits:
  files:
    - README.md
  message: /updated readme.*|update readme.*s|update docs.*|PSGallery Version.*|update appveyor.*/
only_commits:
  files:
    - ctxal-sdk/
pull_requests:
  do_not_increment_build_number: true
build_script:
- ps: |
    Install-PackageProvider -Name NuGet -Force | Out-Null
    find-module -Repository PSGallery -Name PowerShellGet | Out-Null
    Install-Module -Name PowerShellGet -Force -Repository PSGallery -SkipPublisherCheck | Out-Null
    find-module -Repository PSGallery -Name PSScriptAnalyzer | Out-Null
    Install-Module -Name PSScriptAnalyzer -Force -Repository PSGallery -SkipPublisherCheck | Out-Null
    find-module -Repository PSGallery -Name Pester | Out-Null
    Install-Module -Name Pester -Force -Repository PSGallery -SkipPublisherCheck | Out-Null
    find-module -Repository PSGallery -Name PSDeploy | Out-Null
    Install-Module -Name PSDeploy -Force -Repository PSGallery -SkipPublisherCheck | Out-Null
    find-module -Repository PSGallery -Name posh-git | Out-Null
    Install-Module -Name posh-git -Force -Repository PSGallery -SkipPublisherCheck | Out-Null
    $env:Path += ";$env:ProgramFiles\Git\cmd"
test_script:
  - ps: |
      write-verbose "Running Pester..."
      $pest = Invoke-Pester -passthru -verbose
      if ($pest.FailedCount -gt 0) { 
        throw "$($pest.FailedCount) tests failed."
        }
deploy_script:
  - git config --global credential.helper store
  - ps: Add-Content "$env:USERPROFILE\.git-credentials" "https://$($env:github):x-oauth-basic@github.com`n"
  - git config --global user.email "ryan@ryancbutler.com"
  - git config --global user.name "Ryan Butler"
  - git config --global core.autocrlf false
  - git config --global core.safecrlf false
  - ps: |
      write-verbose "Building Docs..."
      . .\AppVeyor\builddocs.ps1 -verbose
      Write-Verbose "Deploying..."
      . .\AppVeyor\deploy.ps1 -verbose
environment:
  PSGKey:
    secure: XbgpBX+B+lBgfWt4379Ez1823W4nLM2zPlOWWvw8zGrvKmZD7/uIlpLYrW4zpjMb
  github:
    secure: qJwCE47jamnSv6Au8wD9CcJmovghdkcm/qoX0IjWa3SDGaeZkGQlQMUlfW9RlsHe